### PR TITLE
Make UdpSender lazy to be able to recover from early DNS issues

### LINKED ISSUE #369: getTracer() fails when the UDP socket hostname isn't resolvable
We had this backtrace recently when a developer had a bad minikube configuration.
```Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.RuntimeException: TUDPTransport cannot connect:
    at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.newThriftUdpClient(ThriftUdpTransport.java:57)
    at com.uber.jaeger.senders.UdpSender.<init>(UdpSender.java:54)
    at com.uber.jaeger.Configuration$ReporterConfiguration.getSender(Configuration.java:328)
    at com.uber.jaeger.Configuration$ReporterConfiguration.getReporter(Configuration.java:335)
    at com.uber.jaeger.Configuration$ReporterConfiguration.access$000(Configuration.java:282)
    at com.uber.jaeger.Configuration.getTracerBuilder(Configuration.java:162)
    at com.uber.jaeger.Configuration.getTracer(Configuration.java:172)
...
Caused by: java.net.SocketException: Unresolved address
    at java.net.DatagramSocket.connect(DatagramSocket.java:493)
    at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.newThriftUdpClient(ThriftUdpTransport.java:55)
    ... 19 more
```

Now, for production contexts I can get behind 'broken configs should stop the program', but for developer contexts logging a message would be quite ok. A further aspect is whether the brokenness is actually broken, or transient.

For UDP protocols we cannot tell if the other end is running or not, so we don't know if the endpoint address and port are correct or not in general. Stopping therefore when they are broken in a specific way doesn't seem useful to me: we have to depend on other mechanisms to determine correctness in prod *no matter what*. That makes this qualitatively different to e.g. bad sampler configurations.

e.g. It might be nice to not throw RuntimeError for this at all, and just log it.

### PR DESCRIPTION
**Pull request by pschichtel**
this should close #369

## Which problem is this PR solving?
- Issue #369 

## Short description of the changes
- made the UdpSender lazily create the ThriftUdpTransport instance to prevent early DNS errors from causing initialization errors. This does require locking, which has been implemented using the double-checked locking pattern to reduce the lock overhead for (usually) the majority of send calls.

### CODE REVIEW

**Comment by pschichtel** [comment]
Not entirely sure what would be the right action for that failing test. It seems to have relied on the UdpSender failing during initialization. If we want to keep it that way, we'd have to eagerly trigger the instantiation of the thrift tranport. I have various ways in my hand on how to do that, but I'd prefer not to unless necessary.

**Comment by pschichtel** [comment]
@yurishkuro @pavolloffay it seems like the project is a little inactive right now, or is this simply the wrong place for such a change request?

**Comment by objectiser** [comment]
@pschichtel  Sorry for the delay in looking at this.

> Not entirely sure what would be the right action for that failing test. It seems to have relied on the UdpSender failing during initialization. If we want to keep it that way, we'd have to eagerly trigger the instantiation of the thrift tranport. I have various ways in my hand on how to do that, but I'd prefer not to unless necessary.

I think it would be fine to change the test to check return value is `UdpSender`.

**Comment by yurishkuro** [comment]
I wonder if this is going to fix the more fundamental issue where the agent address may simply change, e.g. due to agent restart.

There was a recent change in the Go client that implemented periodic reconnects: https://github.com/jaegertracing/jaeger-client-go/pull/520

**Comment by pschichtel** [comment]
Updated the commit to fix the test.

@yurishkuro In its current state, this PR will not handle an address change. Once the client has successfully been created, that instance will stay the same. However adding on some kind of periodic rechecking and/or error handling in UdpSender#send should not be hard as a follow-up.

**Comment by yurishkuro** [comment]
@jpkrohling do you still think we should introduce a configuration option?

**Comment by pschichtel** [comment]
The change in that unit test makes me wonder... Would this change break some kind of fallback logic somewhere? It seems that was being tested there.

File: jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/UdpSender.java [hunk 1]
```diff
@@ -54,14 +57,30 @@ public UdpSender(String host, int port, int maxPacketSize) {
...
+
+  private Agent.Client getAgentClient() {
+    Agent.Client localRef = this.agentClient;
+    if (localRef == null) {
+      synchronized (this) {
+        localRef = this.agentClient;
+        if (localRef == null) {
+          udpTransport = ThriftUdpTransport.newThriftUdpClient(host, port);
+          localRef = new Agent.Client(protocolFactory.getProtocol(udpTransport));
+          agentClient = localRef;
```
Comment (jpkrohling) [inline jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/UdpSender.java:72]:
```suggestion
          this.agentClient = localRef;
```

To make it easier to determine the context?

File: jaeger-thrift/src/test/java/io/jaegertracing/thrift/internal/senders/UdpLazinessTest.java [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+ * the License.
+ */
+package io.jaegertracing.thrift.internal.senders;
+
+import org.junit.Test;
+
+public class UdpLazinessTest {
+    @Test
+    public void testLazyInitializationOfAgent() {
+        new UdpSender("unknown-host." + Math.random(), 55555, 0);
```
Comment (jpkrohling) [inline jaeger-thrift/src/test/java/io/jaegertracing/thrift/internal/senders/UdpLazinessTest.java:21]: `.test` is a TLD that exists for this kind of situation. Anything under that TLD is guaranteed to not exist.

```suggestion
        new UdpSender("agent.acme.test", 55555, 0);
```

**Comment by pschichtel** [comment]
> What happens when the agent isn't available and the client keeps trying to send data? Will there be multiple stacktraces in the logs, one per batch? If so, then we definitely need to make this opt-in.

What about only printing the first stacktrace or every n-th ?

**Comment by jpkrohling** [comment]
First stacktrace + positive confirmation once it succeeds sounds good to me.

**Comment by pschichtel** [comment]
I incorporated the suggestions, however I'm not entirely clear on where to handle the logging. I don't think the UdpSender should just swallow the exceptions, I'd say this should be handled at a higher level. I looked at the HttpSender as well and both of them fail in the same way now with this PR: Exception on every call. So any solution should be at a common code path. Either way I'm not sure this is something that should be done in this PR.

**Comment by yurishkuro** [comment]
I expect the Reporter to catch the exceptions, since it processes items off a queue from a background thread, so there's nowhere to re-throw them.

**Comment by jpkrohling** [comment]
> I looked at the HttpSender as well and both of them fail in the same way now with this PR: Exception on every call. So any solution should be at a common code path. Either way I'm not sure this is something that should be done in this PR.

Agree that this shouldn't be done in this PR. Would you please open an issue with this idea?

**Comment by pschichtel** [comment]
So I think we are done here, right?

**Comment by pschichtel** [comment]
Follow up about the logging can be found at #729
